#!/usr/bin/bash
if [ -e ./Configuration ] ; then
    echo ""
else
    echo "No Configuration file."
    exit 1
fi
. ./Configuration
python3 -m venv venv
. ./venv/bin/activate
pip install requests
deactivate

